version: '3.8'

services:
  web:
    build: .
    ports:
      - "9080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=OnlineEzcaneSistemiDB;User Id=sa;Password=Sifre123!;TrustServerCertificate=True;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Sifre123!
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data: